describe('sauce', () => {
   
    it('Prueba registro usuario', () => {
      cy.visit('https://automationexercise.com/')
      cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
      cy.get('[data-qa="signup-name"]').type('menganito')
      cy.get('[data-qa="signup-email"]').type('lllfvernrgua@gneil.com')
      cy.get('[data-qa="signup-button"]').click()
      cy.get('#id_gender1').click()
      cy.get('#password').type('contrasena')
      cy.get('[data-qa="days"]').select('23')
      cy.get('[data-qa="months"]').select('June')
      cy.get('[data-qa="years"]').select('1980')
      cy.get('#newsletter').click()
      cy.get('#optin').click()
      cy.get('[data-qa="first_name"]').type('Menganito')
      cy.get('[data-qa="last_name"]').type('De tal')
      cy.get('[data-qa="company"]').type('Jormaneva')
      cy.get('[data-qa="address"]').type('Micasita')
      cy.get('[data-qa="address2"]').type('Micasita 2')
      cy.get('[data-qa="country"]').select('Canada')
      cy.get('[data-qa="state"]').type('Vancoover')
      cy.get('[data-qa="city"]').type('Mi barrio')
      cy.get('[data-qa="zipcode"]').type('12345')
      cy.get('[data-qa="mobile_number"]').type('1234567890')
      cy.get('[data-qa="create-account"]').click()
      cy.get('[data-qa="continue-button"]').click()
      cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
      cy.get('[data-qa="continue-button"]').click()
    })
})